# Generated by Django 4.0.5 on 2022-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douryou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whyjoin',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
