# Generated by Django 4.0.5 on 2022-09-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douryou_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='douryou_login',
            name='whyjoin',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='applyluggageadliodtmet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='applypurchasefrancbise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='appy_job_requirement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='education_loan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='travel_insurance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='your_requirement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
    ]
