# Generated by Django 4.0.5 on 2022-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douryou_user', '0002_douryou_login_whyjoin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douryou_login',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='douryouimages/userimages'),
        ),
        migrations.AlterField(
            model_name='douryou_login',
            name='whyjoin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
