# Generated by Django 4.0.5 on 2022-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddnewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('video_title', models.CharField(max_length=255)),
                ('select_seller', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('thumbnail_link', models.CharField(max_length=255)),
            ],
        ),
    ]
